### ISSUE TITLE
提示更换网络

### ISSUE THREAD

**Issue by liangw1024** [rialll/fuckZXJY#3]

**Comment by rialll** [comment]
请提供联系方式 把users.json 发给我

**Comment by azmm1314** [comment]
3014586288

**Comment by liangw1024** [comment]
感谢，问题已经解决是没有填写设备id导致的

**Comment by azmm1314** [comment]
你好 想问一下你是怎么运行的 我运行出来的是开源地址

> 感谢，问题已经解决是没有填写设备ID导致的

**Comment by Live92** [comment]
> 感谢，问题已经解决是没有填写设备id导致的
在本地怎么运行，需要pip再安装三方库吗？我运行的是报错...
