### ISSUE TITLE
已亲测可用！感谢开源大大

### ISSUE THREAD

**Issue by bylengfeng** [rialll/fuckZXJY#6]
日志：
项目地址：https://github.com/rialll/fuckZXJY
获取 Token 成功: 2b1c813****918412d1
登录成功，UID: 5t6BmQ=
签到成功: 打卡成功,待老师审核

**Comment by azmm1314** [comment]
你好，想问一下我运行之后就出来个开源地址 这是什么问题

**Comment by azmm1314** [comment]
D:\edg浏览器\依赖>python index.py
项目地址：https://github.com/rialll/fuckZXJY

D:\edg浏览器\依赖>
