### ISSUE TITLE
大佬疑似作弊

### ISSUE THREAD

**Issue by sterobun** [rialll/fuckZXJY#8]

**Comment by rialll** [comment]
尚不知检测了什么,等到我这边复现后在研究下。

**Comment by xixifeixi** [comment]
蹲一下

**Comment by rialll** [comment]
![112233](https://github.com/rialll/fuckZXJY/assets/48402335/edff181e-2655-448d-98fc-7b566e9feba8)
应该是被官方看到了,喊我写这个的目前并未触发作弊

**Comment by xixifeixi** [comment]
大佬，这个咋运行啊，我运行起来报错：登录失败，错误信息:登录过程中出现了网络错误，请关闭APP切换网络后重新再试

**Comment by xixifeixi** [comment]
> > 大佬，这个咋运行啊，我运行起来报错：登录失败，错误信息：登录过程中出现了网络错误，请关闭APP切换网络后重新再试
> 
> 检查设备ID是否填写

怎么部署云函数？大佬

**Comment by qimu666** [comment]
> ![112233](https://user-images.githubusercontent.com/48402335/276322266-edff181e-2655-448d-98fc-7b566e9feba8.png) 应该是被官方看到了,喊我写这个的目前并未触发作弊


作者你好，你遇到的这个会有什么影响吗

**Comment by xixifeixi** [comment]
dotoken怎么获取？
